config/routes.rb
Rails.application.routes.draw do
  root 'books#home'

  resources :books
  resources :borrows, only: [:index, :create, :destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/register', to: 'users#new', as: 'register'
  post '/users', to: 'users#create'

  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :borrows, dependent: :destroy
  has_many :users, through: :borrows

  validates :title, :author, :publish_year, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["author", "created_at", "id", "publish_year", "title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["borrows"]
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :started_at, presence: true
  validate :book_available, on: :create

  def book_available
    if book.borrows.where(ended_at: nil).exists?
      errors.add(:book, "is already borrowed")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :borrows, dependent: :destroy
  has_many :books, through: :borrows

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result.page(params[:page])
  end

  def show
    @borrow = @book.borrows.find_by(user: current_user, ended_at: nil) || Borrow.new
    @borrow_history = @book.borrows.order(started_at: :desc)
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: t('notices.book_created')
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: t('notices.book_updated')
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: t('notices.book_destroyed')
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :publish_year)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :require_login

  def index
    @active_borrows = current_user.borrows.where(ended_at: nil).page(params[:page]).per(5)
    @borrow_history = current_user.borrows.where.not(ended_at: nil).order(ended_at: :desc).page(params[:history_page]).per(5)
  end

  def create
    @borrow = Borrow.new(borrow_params)
    @borrow.user = current_user
    @borrow.started_at = Time.current

    if @borrow.save
      redirect_to borrows_path, notice: t('notices.borrow_created')
    else
      redirect_to @borrow.book, alert: t('notices.cannot_borrow', errors: @borrow.errors.full_messages.join(", "))
    end
  end

  def destroy
    @borrow = Borrow.find(params[:id])
    @borrow.update(ended_at: Time.current)
    redirect_to borrows_path, notice: t('notices.borrow_returned')
  end

  private

  def borrow_params
    params.require(:borrow).permit(:book_id)
  end

  def require_login
    unless current_user
      redirect_to login_path, alert: t('alerts.must_be_logged_in')
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: t('notices.logged_in')
    else
      flash.now[:alert] = t('alerts.invalid_email_or_password')
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: t('notices.logged_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Inscription réussie'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: 'Mise à jour réussie'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_available?(book)
    book.borrows.where(ended_at: nil).empty?
  end
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="card h-100">
  <div class="card-body">
    <h5 class="card-title"><strong><%= t('books.show.book_details.title') %>:</strong> <%= book.title %></h5>
    <h6 class="card-text"><strong><%= t('books.show.book_details.author') %>:</strong> <%= book.author %></h6>
    <p class="card-text"><strong><%= t('books.show.book_details.publish_year') %>:</strong> <%= book.publish_year %></p>
    <p class="card-text">
      <strong><%= t('books.show.book_details.availability') %>:</strong>
      <% if book_available?(book) %>
        <span class="text-success"><%= t('books.show.book_details.available') %></span>
      <% else %>
        <span class="text-danger"><%= t('books.show.book_details.unavailable') %></span>
      <% end %>
    </p>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, t('errors.template.header.one'), t('errors.template.header.other')) %> <%= t('errors.messages.prohibited', model: t('activerecord.models.book')) %></h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, t('books.form.enter_title'), class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: t('books.form.enter_title') %>
  </div>

  <div class="mb-3">
    <%= form.label :author, t('books.form.enter_author'), class: "form-label" %>
    <%= form.text_field :author, class: "form-control", placeholder: t('books.form.enter_author') %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_year, t('books.form.enter_publish_year'), class: "form-label" %>
    <%= form.number_field :publish_year, class: "form-control", placeholder: t('books.form.enter_publish_year') %>
  </div>

  <div class="mb-3 text-center">
    <%= form.submit t('books.form.save_book'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container mt-5">
  <h1><%= t('books.edit.edit_book') %></h1>
  <%= render 'form', book: @book %>
  <%= link_to t('books.edit.back_to_books'), books_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/books/home.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body d-flex flex-column">
          <h3 class="card-title">Accéder aux Emprunts</h3>
          <p class="card-text">Consultez et gérez vos emprunts de livres.</p>
          <% if current_user %>
            <%= link_to 'Voir mes emprunts', borrows_path, class: 'btn btn-primary mt-auto' %>
          <% else %>
            <p class="card-text text-muted">Veuillez vous connecter pour accéder à vos emprunts.</p>
            <%= link_to 'Se connecter', login_path, class: 'btn btn-primary mt-2' %>
            <%= link_to "S'inscrire", register_path, class: 'btn btn-secondary mt-2' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body d-flex flex-column">
          <h3 class="card-title">Accéder au Catalogue</h3>
          <p class="card-text">Parcourez notre vaste collection de livres disponibles à l'emprunt. Découvrez de nouveaux auteurs et titres dès aujourd'hui.</p>
          <%= link_to 'Voir le catalogue', books_path, class: 'btn btn-primary mt-auto' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4 text-center"><%= t('books.index.title') %></h1>

  <div class="row mb-3">
    <div class="col-12">
      <%= search_form_for @q, url: books_path, method: :get, class: 'form-inline justify-content-center' do |f| %>
        <div class="input-group">
          <%= f.search_field :title_or_author_cont, placeholder: t('books.index.search_placeholder'), class: 'form-control' %>
          <div class="input-group-append">
            <%= f.submit t('books.index.search_button'), class: 'btn btn-outline-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-4 mb-4">
        <%= link_to book, class: 'text-decoration-none card-link' do %>
          <%= render book %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="text-center">
    <%= paginate @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container mt-5">
  <h1><%= t('books.new.add_book') %></h1>
  <%= render 'form', book: @book %>
  <%= link_to t('books.new.back_to_books'), books_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/books/show.html.erb
<div class="container mt-5">
  <div class="card mb-4">
    <div class="card-body">
      <%= render @book %>

      <% if @borrow.persisted? %>
        <%= button_to t('books.show.return_book'), borrow_path(@borrow), method: :delete, class: 'btn btn-danger mt-3' %>
      <% else %>
        <%= form_with model: @borrow, url: borrows_path, local: true do |form| %>
          <%= form.hidden_field :book_id, value: @book.id %>
          <%= form.submit t('books.show.borrow_book'), class: 'btn btn-primary mt-3' %>
        <% end %>
      <% end %>

      <div class="mt-3">
        <%= link_to t('books.show.edit_book'), edit_book_path(@book), class: 'btn btn-warning' %>
        <button class="btn btn-info" data-bs-toggle="collapse" data-bs-target="#borrowHistory" aria-expanded="false" aria-controls="borrowHistory">
          <%= t('books.show.view_borrow_history') %>
        </button>
      </div>
    </div>
  </div>

  <div class="collapse mt-4" id="borrowHistory">
    <div class="card card-body">
      <h3><%= t('books.show.borrow_history.title') %></h3>
      <table class="table">
        <thead>
        <tr>
          <th scope="col"><%= t('books.show.borrow_history.user') %></th>
          <th scope="col"><%= t('books.show.borrow_history.start_date') %></th>
          <th scope="col"><%= t('books.show.borrow_history.end_date') %></th>
        </tr>
        </thead>
        <tbody>
        <% @borrow_history.each do |borrow| %>
          <tr>
            <td><%= borrow.user.first_name %> <%= borrow.user.last_name %> (<%= borrow.user.email %>)</td>
            <td><%= borrow.started_at.strftime("%d/%m/%Y") %></td>
            <td><%= borrow.ended_at.present? ? borrow.ended_at.strftime("%d/%m/%Y") : t('books.show.borrow_history.currently_borrowed') %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/borrows/_borrow.html.erb
<div class="col-md-4 mb-4">
  <div class="card h-100">
    <div class="card-body">
      <h5 class="card-title"><strong><%= t('books.show.book_details.title') %>:</strong> <%= borrow.book.title %></h5>
      <p class="card-text"><strong><%= t('books.show.book_details.author') %>:</strong> <%= borrow.book.author %></p>
      <p class="card-text"><strong><%= t('books.show.book_details.publish_year') %>:</strong> <%= borrow.book.publish_year %></p>
      <p class="card-text">
        <strong><%= t('books.show.book_details.availability') %>:</strong>
        <% if book_available?(borrow.book) %>
          <span class="text-success"><%= t('books.show.book_details.available') %></span>
        <% else %>
          <span class="text-danger"><%= t('books.show.book_details.unavailable') %></span>
        <% end %>
      </p>
      <p class="card-text"><strong><%= t('borrows.index.start_date') %>:</strong> <%= borrow.started_at.strftime("%d/%m/%Y") %></p>
      <% if borrow.ended_at.present? %>
        <p class="card-text"><strong><%= t('borrows.index.end_date') %>:</strong> <%= borrow.ended_at.strftime("%d/%m/%Y") %></p>
      <% else %>
        <p class="card-text"><strong><%= t('borrows.index.end_date') %>:</strong> <%= t('borrows.index.currently_borrowed') %></p>
        <%= button_to t('books.show.return_book'), borrow_path(borrow), method: :delete, class: 'btn btn-danger' %>
      <% end %>
    </div>
  </div>
</div>

app/views/borrows/index.html.erb
<div class="container mt-5">
  <h1><%= t('borrows.index.title') %></h1>

  <ul class="nav nav-tabs" id="borrowTabs" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="active-borrows-tab" data-bs-toggle="tab" href="#active-borrows" role="tab" aria-controls="active-borrows" aria-selected="true"><%= t('borrows.index.active_borrows') %></a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="borrow-history-tab" data-bs-toggle="tab" href="#borrow-history" role="tab" aria-controls="borrow-history" aria-selected="false"><%= t('borrows.index.borrow_history') %></a>
    </li>
  </ul>

  <div class="tab-content" id="borrowTabsContent">
    <div class="tab-pane fade show active" id="active-borrows" role="tabpanel" aria-labelledby="active-borrows-tab">
      <div class="row mt-3">
        <% @active_borrows.each do |borrow| %>
          <%= render 'borrows/borrow', borrow: borrow %>
        <% end %>
      </div>
      <div class="text-center">
        <%= paginate @active_borrows %>
      </div>
    </div>
    <div class="tab-pane fade" id="borrow-history" role="tabpanel" aria-labelledby="borrow-history-tab">
      <div class="row mt-3">
        <% @borrow_history.each do |borrow| %>
          <%= render 'borrows/borrow', borrow: borrow %>
        <% end %>
      </div>
      <div class="text-center">
        <%= paginate @borrow_history, param_name: :history_page %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GestionBiblioHoussais</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'GestionBiblioHoussais', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Emprunts', borrows_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('navbar.books'), books_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('navbar.new_book'), new_book_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to t('navbar.logout'), logout_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('navbar.login'), login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('navbar.register'), register_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <% if key == 'notice' %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% elsif key == 'alert' %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2>Modifier le profil</h2>
        </div>
        <div class="card-body">
          <%= form_with(model: @user, url: user_path(@user), local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :first_name, "Prénom", class: "form-label" %>
              <%= form.text_field :first_name, class: "form-control", placeholder: "Entrez votre prénom" %>
            </div>

            <div class="mb-3">
              <%= form.label :last_name, "Nom", class: "form-label" %>
              <%= form.text_field :last_name, class: "form-control", placeholder: "Entrez votre nom" %>
            </div>

            <div class="mb-3">
              <%= form.label :email, class: "form-label" %>
              <%= form.email_field :email, class: "form-control", placeholder: "Entrez votre email" %>
            </div>

            <div class="mb-3">
              <%= form.label :password, "Mot de passe", class: "form-label" %>
              <%= form.password_field :password, class: "form-control", placeholder: "Laissez vide si inchangé" %>
            </div>

            <div class="mb-3">
              <%= form.label :password_confirmation, "Confirmation du mot de passe", class: "form-label" %>
              <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirmez votre mot de passe" %>
            </div>

            <div class="mb-3 text-center">
              <%= form.submit 'Mettre à jour', class: "btn btn-primary" %>
            </div>
          <% end %>

          <%= link_to 'Retour', root_path, class: "btn btn-secondary mt-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2><%= t('users.new.sign_up') %></h2>
        </div>
        <div class="card-body">
          <%= form_with(model: @user, local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :first_name, t('users.new.first_name'), class: "form-label" %>
              <%= form.text_field :first_name, class: "form-control", placeholder: t('users.new.first_name') %>
            </div>

            <div class="mb-3">
              <%= form.label :last_name, t('users.new.last_name'), class: "form-label" %>
              <%= form.text_field :last_name, class: "form-control", placeholder: t('users.new.last_name') %>
            </div>

            <div class="mb-3">
              <%= form.label :email, t('users.new.email'), class: "form-label" %>
              <%= form.email_field :email, class: "form-control", placeholder: t('users.new.email') %>
            </div>

            <div class="mb-3">
              <%= form.label :password, t('users.new.password'), class: "form-label" %>
              <%= form.password_field :password, class: "form-control", placeholder: t('users.new.password') %>
            </div>

            <div class="mb-3">
              <%= form.label :password_confirmation, t('users.new.password_confirmation'), class: "form-label" %>
              <%= form.password_field :password_confirmation, class: "form-control", placeholder: t('users.new.password_confirmation') %>
            </div>

            <div class="mb-3 text-center">
              <%= form.submit t('users.new.register'), class: "btn btn-primary" %>
            </div>
          <% end %>

          <%= link_to t('sessions.new.login'), login_path, class: "btn btn-secondary mt-3" %>
        </div>
      </div>
    </div>
  </div>
</div>